const nutmeg_abi = `[
   {
      "anonymous":false,
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"addPoolEvent",
      "type":"event",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0xaf34faf75d3145f35bbbac30e5a4ee7bdcce5f49268859df1a013baa102eca1b"
   },
   {
      "anonymous":false,
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"borrowEvent",
      "type":"event",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0x22505539bbbf00d2acb21f575cad8d3b6391fbeaf695ffaa373b575d9f7d03dd"
   },
   {
      "anonymous":false,
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"removeLiquidityEvent",
      "type":"event",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0xcce6f96409adc970e72b502be0f79b5d20b1878c27659f1368abfce8139fa555"
   },
   {
      "anonymous":false,
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"stakeEvent",
      "type":"event",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0xdd896aa374850d8e04317b5aeb7adadc818f31150c0dc804fe7c0da09bb66772"
   },
   {
      "inputs":[
         
      ],
      "name":"CURR_ADAPTER",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x639dc527"
   },
   {
      "inputs":[
         
      ],
      "name":"CURR_POSITION_ID",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x5400e01b"
   },
   {
      "inputs":[
         
      ],
      "name":"DEPOSIT_COUNTER",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x5a6f9298"
   },
   {
      "inputs":[
         
      ],
      "name":"EXECUTION_LOCK",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0xa4b407e4"
   },
   {
      "inputs":[
         
      ],
      "name":"LIQUIDATION_COMMISSION",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x3d31fbb4"
   },
   {
      "inputs":[
         
      ],
      "name":"MAX_INTEREST_RATE_PER_BLOCK",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x81d3a1c2"
   },
   {
      "inputs":[
         
      ],
      "name":"MAX_NUM_POOL",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0xd2745968"
   },
   {
      "inputs":[
         
      ],
      "name":"MIN_INTEREST_RATE_PER_BLOCK",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x9befd223"
   },
   {
      "inputs":[
         
      ],
      "name":"NUT_ADDRESS",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x68623d42"
   },
   {
      "inputs":[
         
      ],
      "name":"POOL_LOCK",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x449b5392"
   },
   {
      "inputs":[
         
      ],
      "name":"POSITION_COUNTER",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0xeb289421"
   },
   {
      "inputs":[
         
      ],
      "name":"acceptGovernor",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0xe58bb639"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"adapterMap",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x8ccab138"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"adapters",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x4ef501ac"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"creditEventMap",
      "outputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0xd25973aa"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"depositMap",
      "outputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x24a0f1a5"
   },
   {
      "inputs":[
         
      ],
      "name":"governor",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x0c340a24"
   },
   {
      "inputs":[
         
      ],
      "name":"pendingGovernor",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0xe3056a34"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"poolMap",
      "outputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x5b673532"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"pools",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0xac4afa38"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"positionMap",
      "outputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x0b5f78a1"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"setPendingGovernor",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0xf235757f"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"initialize",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0xc4d66de8"
   },
   {
      "inputs":[
         
      ],
      "name":"getGovernor",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x4fc07d75"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"getDepositIds",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0xc5ebc2f7"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"getPositionIds",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x28fe7031"
   },
   {
      "inputs":[
         
      ],
      "name":"getCurrPositionId",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x7e7768ae"
   },
   {
      "inputs":[
         
      ],
      "name":"getNextPositionId",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x067f4ddd"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"getPosition",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0xeb02c301"
   },
   {
      "inputs":[
         
      ],
      "name":"getPools",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x673a2a1f"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"getPool",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0xbbe4f6db"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"addPool",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0x32a9caba"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"updateInterestRates",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0x01fda53b"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"stake",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0x0c51b88f"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"unstake",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0xa2bc66be"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"getPositionInterestExt",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x51aa825a"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"getPoolInfo",
      "outputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x06bfa938"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"getPositionInterest",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x470ce5f2"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"updateInterestRateAdjustment",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0x8033db42"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"_getCollateralRatioPct",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0xb90306ed"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"getMaxBorrowAmountExt",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x2645866f"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"getMaxBorrowAmount",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x80b88a2e"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"getDeposit",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0xc35082a9"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"addAdapter",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0x60d54d41"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"removeAdapter",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0x585cd34b"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"execute",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0x710a9f68"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"borrow",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0xfbf37739"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"_getRepayAmount",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"pure",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0xce56378a"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"repay",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0x22867d78"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"liquidate",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0xbcbaf487"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"settleCreditEvent",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0x4884822f"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"addCollToken",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function",
      "constant":"undefined",
      "payable":"undefined",
      "signature":"0x554028ba"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"hasCreditEvent",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0xf2016b7e"
   },
   {
      "inputs":[
         [
            "Object"
         ]
      ],
      "name":"getBank",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x83e0c31d"
   },
   {
      "inputs":[
         [
            "Object"
         ],
         [
            "Object"
         ],
         [
            "Object"
         ]
      ],
      "name":"getEarnedInterest",
      "outputs":[
         [
            "Object"
         ]
      ],
      "stateMutability":"view",
      "type":"function",
      "constant":true,
      "payable":"undefined",
      "signature":"0x265c03aa"
   }
]`;

export default nutmeg_abi;