/*
 *
 * FarmPage constants
 *
 */

export const CHANGE_FARM_ASSET = 'app/FarmPage/CHANGE_FARM_ASSET';
export const CHANGE_FARM_ASSET_SUCCESS = 'app/FarmPage/CHANGE_FARM_ASSET_SUCCESS';

export const CHANGE_FARM_COLLATERAL_ASSET = 'app/FarmPage/CHANGE_FARM_COLLATERAL_ASSET';
export const CHANGE_FARM_COLLATERAL_ASSET_SUCCESS = 'app/FarmPage/CHANGE_FARM_COLLATERAL_ASSET_SUCCESS';

export const CHANGE_FARM_BORROW_ASSET = 'app/FarmPage/CHANGE_FARM_BORROW_ASSET';
export const CHANGE_FARM_BORROW_ASSET_SUCCESS = 'app/FarmPage/CHANGE_FARM_BORROW_ASSET_SUCCESS';

export const CHANGE_COLLATERAL_AMOUNT = 'app/FarmPage/CHANGE_COLLATERAL_AMOUNT';
export const CHANGE_COLLATERAL_AMOUNT_SUCCESS = 'app/FarmPage/CHANGE_COLLATERAL_AMOUNT_SUCCESS';

export const UPDATE_INPUT_VALUE = 'app/FarmPage/UPDATE_INPUT_VALUE';
export const UPDATE_INPUT_VALUE_SUCCESS = 'app/FarmPage/UPDATE_INPUT_VALUE_SUCCESS';

export const CHANGE_BORROW_AMOUNT = 'app/FarmPage/CHANGE_BORROW_AMOUNT';
